install:
- SET PATH=%PATH%;C:\MinGW\bin
- ps: Start-FileDownload http://static.rust-lang.org/dist/$env:PLATFORM -FileName rust.exe
- rust.exe /VERYSILENT /NORESTART /DIR="C:\Program Files\Rust"
- SET PATH=%PATH%;C:\Program Files\Rust\bin
- rustc -vV
- cargo -V
platform:
- rust-1.3.0-i686-pc-windows-gnu.exe
# To build against multiple rust versions add them here
build_script:
- cargo build
# Use winbundle to deploy itself
- target\debug\winbundle.exe bundle target\debug\winbundle\ target\debug\winbundle.exe
test_script:
- cargo test
artifacts:
- path: target/debug/winbundle
  name: winbundle
